// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  JSONPathDataType = 1,
  Union = 2,
  StringLiteral = 3,
  NumberLiteral = 4,
  BooleanLiteral = 5,
  Primitive = 6,
  Object = 9,
  Property = 10,
  PropertyName = 11,
  Array = 18,
  ArrayItem = 19
