// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {jsonPathDataTypeStyleTags} from "./data-type-style-tags"
const spec_identifier = {__proto__:null,true:64, false:66}
export const parser = LRParser.deserialize({
  version: 14,
  states: "&fOVQPOOOOQO'#C_'#C_OOQO'#C`'#C`OOQO'#Cb'#CbOnQPO'#CeOyQPO'#CnOOQO'#Cx'#CxO!TQPO'#CwOOQO'#C^'#C^QOQPOOOOQO'#Ca'#CaOOQO'#Cg'#CgO!fQPO'#DOOOQO,59P,59PO!nQPO,59PO!sQPO'#CfO!{QPO'#DPOOQO,59Y,59YO#TQPO,59YOOQO'#Co'#CoO#YQPO'#CoOVQPO'#CsO#_QPO,59cOqQPO'#CqO#pQPO,59jOOQO1G.k1G.kOVQPO,59QO#xQPO,59QO#}QPO'#CrO$UQPO,59kOOQO1G.t1G.tOVQPO,59ZOOQO,59_,59_OOQO-E6q-E6qOOQO,59],59]OOQO-E6o-E6oOOQO1G.l1G.lOVQPO1G.lOOQO,59^,59^OOQO-E6p-E6pOOQO1G.u1G.uOOQO7+$W7+$W",
  stateData: "$^~OjOS~OWSOaTOmPOnQOoROpYOqYO~OV]O[_OoZO~O[dO`aO~PVOdeOhkX_kX`kXVkX~O_gOVrX~OViO~O]kO^jO~O_lO`sX~O`nO~O^oO~OdeOhka_ka`kaVka~O_gOVra~O^uO~O[dO~PVO_lO`sa~O",
  goto: "#mtPPu!V!V!V!VPP!V!`!fPPPPPP!V!jP!p!v!|PPP#S#[PPPPP#g#jQXOScTlQtjQxoRyu_UOTejlouQ[SRrgT_SgQ`TRvlQh[RshQm`RwmQfVRqf]WOTjlou[VOTjlouRpeR^SRbT",
  nodeNames: "⚠ JSONPathDataType Union StringLiteral NumberLiteral BooleanLiteral Primitive } { Object Property PropertyName ... ? : , ] [ Array ArrayItem |",
  maxTerm: 35,
  nodeProps: [
    ["openedBy", 7,"{",16,"["],
    ["closedBy", 8,"}",17,"]"]
  ],
  propSources: [jsonPathDataTypeStyleTags],
  skippedNodes: [0],
  repeatNodeCount: 3,
  tokenData: "(]~RcXY!^YZ!^]^!^pq!^rs!c|}${}!O%Q!O!P&z!Q!R%Z!R![&i![!]']!a!b'b!c!}'g!}#O'r#P#Q'w#T#o'g#o#p'|#p#q(R#q#r(W~!cOj~~!fWpq!cqr!crs#Os#O!c#O#P#T#P;'S!c;'S;=`$u<%lO!c~#TOm~~#WXrs!c!P!Q!c#O#P!c#U#V!c#Y#Z!c#b#c!c#f#g!c#h#i!c#i#j#s~#vR!Q![$P!c!i$P#T#Z$P~$SR!Q![$]!c!i$]#T#Z$]~$`R!Q![$i!c!i$i#T#Z$i~$lR!Q![!c!c!i!c#T#Z!c~$xP;=`<%l!c~%QO_~~%TQ!Q!R%Z!R![&i~%`Rn~!O!P%i!g!h%}#X#Y%}~%lP!Q![%o~%tRn~!Q![%o!g!h%}#X#Y%}~&QR{|&Z}!O&Z!Q![&a~&^P!Q![&a~&fPn~!Q![&a~&nSn~!O!P%i!Q![&i!g!h%}#X#Y%}~&}P!O!P'Q~'TP!O!P'W~']O[~~'bO^~~'gO]~~'lQo~!c!}'g#T#o'g~'wOa~~'|O`~~(ROW~~(WOd~~(]OV~",
  tokenizers: [0],
  topRules: {"JSONPathDataType":[0,1]},
  specialized: [{term: 31, get: (value: keyof typeof spec_identifier) => spec_identifier[value] || -1}],
  tokenPrec: 0
})
