name: Build, Test and Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - name: Setup GitHub Pages
        uses: actions/configure-pages@v4
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright browsers
        run: npx playwright install chromium --with-deps
      - name: Build @jsonpath-tools/jsonpath
        run: npm run build --workspace @jsonpath-tools/jsonpath
      - name: Build @jsonpath-tools/codemirror-lang-jsonpath
        run: npm run build --workspace @jsonpath-tools/codemirror-lang-jsonpath
      - name: Build @jsonpath-tools/jsonpath-editor-react
        run: npm run build --workspace @jsonpath-tools/jsonpath-editor-react
      - name: Build @jsonpath-tools/jsonpath-playground
        run: npm run build --workspace @jsonpath-tools/jsonpath-playground
      #- name: Run lint
      #  run: npm run lint --workspaces --if-present
      - name: Run tests
        run: npm run test --workspaces --if-present
      - name: Run end-to-end tests
        run: npm run test:e2e --workspaces --if-present
      - name: Build @jsonpath-tools/documentation
        run: |
          npm run typedoc --workspace @jsonpath-tools/documentation
          npm run build --workspace @jsonpath-tools/documentation
      - name: Upload @jsonpath-tools/jsonpath-playground artifact
        uses: actions/upload-artifact@v4
        with:
          name: jsonpath-playground-build
          path: apps/jsonpath-playground/dist/
      - name: Upload @jsonpath-tools/documentation artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: apps/documentation/.vitepress/dist

  deploy:
    name: Deploy
    if: github.ref == 'refs/heads/main'
    needs: build-test
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Download @jsonpath-tools/jsonpath-playground artifact
        uses: actions/download-artifact@v4
        with:
          name: jsonpath-playground-build
          path: apps/jsonpath-playground/dist/
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4